# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c88ac44fe8e5c49189dc75bdeb3f9ef34894382e833ba09d54e80da47ab5749fabbda707c30de11931459d85c99e4530d540ca26a149ebcecc7ba6677af390e3

test:
  secret_key_base: a5c0f1ca89beabdd2b1351da61e3f2beeed2e07cc8a33fe553157cc0c9ffc744e142fa2d99660c7f0a82c5aaf95d2f03d8c189ba6f4cf164562dd999b6b0040b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
